-- MySQL Script generated by MySQL Workbench
-- Fri Mar  4 16:07:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pipo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pipo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pipo` DEFAULT CHARACTER SET utf8 ;
USE `pipo` ;

-- -----------------------------------------------------
-- Table `pipo`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Escolaridad` (
  `codigo` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `denominacion` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Parte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Parte` (
  `codigo` VARCHAR(50) NOT NULL,
  `curp` VARCHAR(20) NULL,
  `correo` VARCHAR(350) NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `primerApellido` VARCHAR(50) NOT NULL,
  `segundoApellido` VARCHAR(50) NULL,
  `nacimiento` DATE NULL,
  `sexo` BIT NULL,
  `ocupacion` VARCHAR(100) NULL,
  `Escolaridad_codigo` TINYINT(1) UNSIGNED NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_Parte_Escolaridad`
    FOREIGN KEY (`Escolaridad_codigo`)
    REFERENCES `pipo`.`Escolaridad` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Tipo` (
  `codigo` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `denominacion` VARCHAR(75) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Denuncia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Denuncia` (
  `folio` VARCHAR(50) NOT NULL,
  `titulo` VARCHAR(75) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `momento` DATETIME NOT NULL DEFAULT NOW(),
  `fecha` DATETIME NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `municipio` VARCHAR(100) NOT NULL,
  `colonia` VARCHAR(100) NULL,
  `calle` VARCHAR(45) NULL,
  `numeroInterior` TINYINT(1) UNSIGNED NULL,
  `numeroExterior` TINYINT(1) UNSIGNED NULL,
  `codigoPostal` VARCHAR(10) NULL,
  `referencias` TINYTEXT NULL,
  `Parte_codigoDenunciante` VARCHAR(50) NULL,
  `Parte_codigoDenunciado` VARCHAR(50) NOT NULL,
  `Tipo_codigo` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`folio`),
  CONSTRAINT `fk_Denuncia_ParteDenunciante`
    FOREIGN KEY (`Parte_codigoDenunciante`)
    REFERENCES `pipo`.`Parte` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Denuncia_ParteDenunciado`
    FOREIGN KEY (`Parte_codigoDenunciado`)
    REFERENCES `pipo`.`Parte` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Denuncia_Tipo1`
    FOREIGN KEY (`Tipo_codigo`)
    REFERENCES `pipo`.`Tipo` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Evidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Evidencia` (
  `Denuncia_folio` VARCHAR(50) NOT NULL,
  `numero` TINYINT(1) NOT NULL,
  `extension` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Denuncia_folio`, `numero`),
  CONSTRAINT `fk_Evidencia_Denuncia`
    FOREIGN KEY (`Denuncia_folio`)
    REFERENCES `pipo`.`Denuncia` (`folio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Estado` (
  `codigo` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `denominacion` VARCHAR(75) NOT NULL,
  `descripcion` TINYTEXT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Organizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Organizacion` (
  `codigo` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `momento` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pipo`.`Monitoreo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pipo`.`Monitoreo` (
  `Denuncia_folio` VARCHAR(50) NOT NULL,
  `Estado_codigo` TINYINT(1) UNSIGNED NOT NULL,
  `Organizacion_codigo` VARCHAR(50) NOT NULL,
  `momento` DATETIME NOT NULL DEFAULT NOW(),
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `observaciones` TEXT NULL,
  PRIMARY KEY (`Denuncia_folio`, `Estado_codigo`, `Organizacion_codigo`),
  CONSTRAINT `fk_Monitoreo_Denuncia`
    FOREIGN KEY (`Denuncia_folio`)
    REFERENCES `pipo`.`Denuncia` (`folio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Monitoreo_Estado`
    FOREIGN KEY (`Estado_codigo`)
    REFERENCES `pipo`.`Estado` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Monitoreo_Organizacion`
    FOREIGN KEY (`Organizacion_codigo`)
    REFERENCES `pipo`.`Organizacion` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
